export const ROLE_KEYS = Object.freeze({
  SYSTEM_ADMIN: 'SYS_ADMIN',
  DORMITORY_ADMIN: 'DORM_CENTER',
  ZONE_MANAGER: 'ZONE_MANAGER',
  READONLY_USER: 'READ_ONLY',
  COUNSELOR: 'COUNSELOR',
  ZONE_ADMIN: 'ZONE_ADMIN',
  REPAIR_WORKER: 'REPAIR_WORKER',
  REPAIR_TEAM: 'REPAIR_TEAM',
  STUDENT: 'STUDENT',
})

export const ROLE_OPTIONS = Object.freeze([
  { value: ROLE_KEYS.SYSTEM_ADMIN, label: '系统管理员', shortLabel: '系统管理' },
  { value: ROLE_KEYS.DORMITORY_ADMIN, label: '宿管中心管理员', shortLabel: '宿管中心' },
  { value: ROLE_KEYS.ZONE_MANAGER, label: '苑区老师', shortLabel: '苑区老师' },
  { value: ROLE_KEYS.READONLY_USER, label: '只读用户', shortLabel: '只读访问' },
  { value: ROLE_KEYS.COUNSELOR, label: '辅导员', shortLabel: '学院管理' },
  { value: ROLE_KEYS.ZONE_ADMIN, label: '苑区管理员', shortLabel: '苑区管理' },
  { value: ROLE_KEYS.REPAIR_WORKER, label: '维修工', shortLabel: '维修工' },
  { value: ROLE_KEYS.REPAIR_TEAM, label: '维修队', shortLabel: '维修队' },
  { value: ROLE_KEYS.STUDENT, label: '学生', shortLabel: '学生服务' },
])

export const SUBSYSTEM_KEYS = Object.freeze({
  BED: 'bed',
  MAINTENANCE: 'maintenance',
  OPINION_COLLECTION: 'opinion-collection',
  SYSTEM: 'system',
})

const maintenanceRoles = [
  ROLE_KEYS.SYSTEM_ADMIN,
  ROLE_KEYS.DORMITORY_ADMIN,
  ROLE_KEYS.ZONE_MANAGER,
  ROLE_KEYS.ZONE_ADMIN,
  ROLE_KEYS.STUDENT,
  ROLE_KEYS.REPAIR_WORKER,
  ROLE_KEYS.REPAIR_TEAM,
]

export const SUBSYSTEMS = Object.freeze([
  {
    id: SUBSYSTEM_KEYS.BED,
    routeName: 'BedWorkspace',
    path: '/bed',
    title: '床位系统',
    description: '管理学生住宿、床位确认与住宿信息变更。',
    icon: 'House',
    roles: [
      ROLE_KEYS.SYSTEM_ADMIN,
      ROLE_KEYS.DORMITORY_ADMIN,
      ROLE_KEYS.ZONE_MANAGER,
      ROLE_KEYS.ZONE_ADMIN,
      ROLE_KEYS.COUNSELOR,
      ROLE_KEYS.STUDENT,
      ROLE_KEYS.READONLY_USER,
    ],
  },
  {
    id: SUBSYSTEM_KEYS.MAINTENANCE,
    routeName: 'MaintenanceWorkspace',
    path: '/maintenance',
    title: '维修系统',
    description: '覆盖报修上报、问题流转、工单处理与验收。',
    icon: 'Tools',
    roles: maintenanceRoles,
  },
  {
    id: SUBSYSTEM_KEYS.OPINION_COLLECTION,
    routeName: 'OpinionCollectionWorkspace',
    path: '/opinion-collection',
    title: '意见征集',
    description: '汇集学生生活意见，推动宿舍服务持续改进。',
    icon: 'ChatDotRound',
    roles: [ROLE_KEYS.SYSTEM_ADMIN, ROLE_KEYS.DORMITORY_ADMIN, ROLE_KEYS.STUDENT],
  },
  {
    id: SUBSYSTEM_KEYS.SYSTEM,
    routeName: 'SystemWorkspace',
    path: '/system',
    title: '系统管理',
    description: '维护用户账号、住宿资源与系统操作记录。',
    icon: 'Setting',
    roles: [ROLE_KEYS.SYSTEM_ADMIN, ROLE_KEYS.DORMITORY_ADMIN],
  },
])

const bedManagementRoles = [
  ROLE_KEYS.SYSTEM_ADMIN,
  ROLE_KEYS.DORMITORY_ADMIN,
  ROLE_KEYS.ZONE_MANAGER,
  ROLE_KEYS.ZONE_ADMIN,
  ROLE_KEYS.COUNSELOR,
]

const accommodationViewRoles = [...bedManagementRoles, ROLE_KEYS.READONLY_USER]

const MODULE_OPERATION_PRIORITY = Object.freeze({
  query: 1,
  create: 2,
  delete: 3,
  edit: 4,
})

export const ACCESS_MODULES = Object.freeze([
  {
    id: 'accommodation-query',
    subsystem: SUBSYSTEM_KEYS.BED,
    routeName: 'AccommodationQuery',
    path: '/bed/accommodation/query',
    legacyPaths: ['/accommodation/query'],
    title: '住宿信息查看',
    group: '住宿信息管理',
    workspaceGroup: '住宿信息查看',
    workspaceGroupOrder: 1,
    workspaceOrder: 1,
    icon: 'Search',
    operation: 'query',
    roles: accommodationViewRoles,
    descriptions: {
      [ROLE_KEYS.SYSTEM_ADMIN]: '查看全校学生住宿与床位使用情况。',
      [ROLE_KEYS.DORMITORY_ADMIN]: '查看全校学生住宿与床位使用情况。',
      [ROLE_KEYS.ZONE_MANAGER]: '查看分管苑区学生住宿与床位使用情况。',
      [ROLE_KEYS.ZONE_ADMIN]: '查看分管苑区学生住宿与床位使用情况。',
      [ROLE_KEYS.COUNSELOR]: '查看全校学生住宿与床位使用情况。',
      [ROLE_KEYS.READONLY_USER]: '只读查看全校学生住宿与床位使用情况。',
    },
  },
  {
    id: 'accommodation-import',
    subsystem: SUBSYSTEM_KEYS.BED,
    routeName: 'AccommodationImport',
    path: '/bed/accommodation/import',
    legacyPaths: ['/accommodation/import'],
    title: '住宿信息导入',
    description: '批量导入学生住宿信息。',
    group: '住宿信息管理',
    workspaceGroup: '住宿信息导入',
    workspaceGroupOrder: 2,
    workspaceOrder: 1,
    icon: 'UploadFilled',
    operation: 'create',
    roles: bedManagementRoles,
  },
  {
    id: 'accommodation-delete',
    subsystem: SUBSYSTEM_KEYS.BED,
    routeName: 'AccommodationDelete',
    path: '/bed/accommodation/delete',
    legacyPaths: ['/accommodation/delete'],
    title: '住宿信息删除',
    description: '删除不再住宿的学生住宿信息。',
    group: '住宿信息管理',
    workspaceGroup: '住宿信息删除',
    workspaceGroupOrder: 4,
    workspaceOrder: 1,
    icon: 'DeleteFilled',
    operation: 'delete',
    tone: 'danger',
    roles: bedManagementRoles,
  },
  {
    id: 'accommodation-change-log',
    subsystem: SUBSYSTEM_KEYS.BED,
    routeName: 'AccommodationChangeLog',
    path: '/bed/accommodation/change-records',
    legacyPaths: ['/accommodation/change-records'],
    title: '住宿信息变更日志',
    description: '查看学生住宿信息的历史变更记录。',
    group: '住宿信息管理',
    workspaceGroup: '住宿信息修改',
    workspaceGroupOrder: 3,
    workspaceOrder: 3,
    icon: 'DocumentChecked',
    operation: 'query',
    roles: [ROLE_KEYS.SYSTEM_ADMIN, ROLE_KEYS.DORMITORY_ADMIN, ROLE_KEYS.ZONE_MANAGER, ROLE_KEYS.ZONE_ADMIN],
  },
  {
    id: 'change-review',
    subsystem: SUBSYSTEM_KEYS.BED,
    routeName: 'ChangeReview',
    path: '/bed/applications/change/review',
    legacyPaths: ['/applications/change/review'],
    title: '住宿信息修改审核',
    description: '审核已提交的住宿信息修改申请。',
    group: '住宿信息管理',
    workspaceGroup: '住宿信息修改',
    workspaceGroupOrder: 3,
    workspaceOrder: 2,
    icon: 'DocumentChecked',
    operation: 'edit',
    roles: [ROLE_KEYS.SYSTEM_ADMIN, ROLE_KEYS.DORMITORY_ADMIN],
  },
  {
    id: 'change-application',
    subsystem: SUBSYSTEM_KEYS.BED,
    routeName: 'ChangeApplication',
    path: '/bed/applications/change/create',
    legacyPaths: ['/applications/change/create', '/accommodation/edit'],
    title: '住宿信息修改申请',
    description: '提交学生住宿与转专业后的信息修改申请。',
    group: '住宿信息管理',
    workspaceGroup: '住宿信息修改',
    workspaceGroupOrder: 3,
    workspaceOrder: 1,
    icon: 'Edit',
    operation: 'edit',
    roles: [ROLE_KEYS.SYSTEM_ADMIN, ROLE_KEYS.DORMITORY_ADMIN, ROLE_KEYS.ZONE_MANAGER, ROLE_KEYS.ZONE_ADMIN, ROLE_KEYS.COUNSELOR],
  },
  /* Disabled pages retained for future restoration.
  {
    id: 'error-information-correction-review',
    subsystem: SUBSYSTEM_KEYS.BED,
    routeName: 'ErrorInformationCorrectionReview',
    path: '/bed/confirmations/error-correction-review',
    legacyPaths: ['/confirmations/error-correction-review'],
    title: '有误信息纠正审核',
    description: '审核学生反馈的住宿信息纠正申请。',
    group: '住宿信息管理',
    icon: 'WarningFilled',
    operation: 'edit',
    roles: [ROLE_KEYS.COUNSELOR],
  },
  {
    id: 'student-confirmation',
    subsystem: SUBSYSTEM_KEYS.BED,
    routeName: 'StudentConfirmation',
    path: '/bed/confirmation',
    legacyPaths: ['/student/confirmation'],
    title: '住宿信息确认',
    description: '核对并确认本人的住宿信息。',
    group: '住宿信息管理',
    icon: 'CircleCheckFilled',
    operation: 'edit',
    roles: [ROLE_KEYS.STUDENT],
  },
  }, */
  {
    id: 'student-bed-information',
    subsystem: SUBSYSTEM_KEYS.BED,
    routeName: 'StudentBedInformation',
    path: '/bed/my-information',
    legacyPaths: ['/student/bed'],
    title: '我的住宿信息',
    description: '查看本人当前住宿与床位信息。',
    group: '住宿信息管理',
    icon: 'View',
    operation: 'query',
    roles: [ROLE_KEYS.STUDENT],
  },
  {
    id: 'bed-allocation',
    subsystem: SUBSYSTEM_KEYS.BED,
    routeName: 'BedAllocation',
    path: '/accommodation/bed-allocation',
    legacyPaths: ['/bed-allocation'],
    title: '寝室床位智能分配',
    description: '为真实新生或自定义人数生成可调整、可导出的床位预分配方案',
    group: '住宿信息',
    icon: 'Grid',
    roles: [ROLE_KEYS.SYSTEM_ADMIN, ROLE_KEYS.DORMITORY_ADMIN],
  },
  {
    id: 'bed-allocation-new',
    subsystem: SUBSYSTEM_KEYS.BED,
    routeName: 'BedAllocationNew',
    path: '/accommodation/bed-allocation-new',
    title: '寝室床位智能分配系统',
    description: '寝室床位智能分配新页面',
    group: '住宿信息',
    icon: 'Grid',
    roles: [ROLE_KEYS.SYSTEM_ADMIN, ROLE_KEYS.DORMITORY_ADMIN],
  },
  {
    id: 'maintenance-workbench',
    subsystem: SUBSYSTEM_KEYS.MAINTENANCE,
    routeName: 'MaintenanceWorkbench',
    path: '/maintenance/workbench',
    title: '维修工作台',
    description: '按当前待办集中处理报修、工单和维修任务。',
    group: '维修工作台',
    icon: 'Tools',
    operation: 'query',
    workspaceVisible: false,
    workspaceRoles: [
      ROLE_KEYS.SYSTEM_ADMIN,
      ROLE_KEYS.DORMITORY_ADMIN,
      ROLE_KEYS.ZONE_MANAGER,
      ROLE_KEYS.ZONE_ADMIN,
      ROLE_KEYS.REPAIR_WORKER,
      ROLE_KEYS.REPAIR_TEAM,
    ],
    roles: maintenanceRoles,
  },
  {
    id: 'maintenance-work-orders',
    subsystem: SUBSYSTEM_KEYS.MAINTENANCE,
    routeName: 'MaintenanceWorkOrders',
    path: '/maintenance/work-orders',
    title: '工单',
    description: '创建、修改、派发和跟进维修工单。',
    group: '维修服务',
    workspaceGroup: '维修服务',
    workspaceGroupOrder: 1,
    workspaceOrder: 1,
    icon: 'Document',
    operation: 'query',
    roles: [
      ROLE_KEYS.SYSTEM_ADMIN,
      ROLE_KEYS.DORMITORY_ADMIN,
      ROLE_KEYS.ZONE_MANAGER,
      ROLE_KEYS.REPAIR_WORKER,
      ROLE_KEYS.REPAIR_TEAM,
    ],
  },
  {
    id: 'maintenance-reports',
    subsystem: SUBSYSTEM_KEYS.MAINTENANCE,
    routeName: 'MaintenanceReports',
    path: '/maintenance/reports',
    title: '报修',
    description: '提交维修问题并查看当前处理进度。',
    group: '维修服务',
    workspaceGroup: '维修服务',
    workspaceGroupOrder: 1,
    workspaceOrder: 2,
    icon: 'EditPen',
    operation: 'create',
    roles: [ROLE_KEYS.SYSTEM_ADMIN, ROLE_KEYS.ZONE_MANAGER],
  },
  {
    id: 'maintenance-operation-log',
    subsystem: SUBSYSTEM_KEYS.MAINTENANCE,
    routeName: 'MaintenanceOperationLog',
    path: '/maintenance/operation-logs',
    title: '日志',
    description: '查看报修和工单的详细操作记录。',
    group: '维修服务',
    workspaceGroup: '维修服务',
    workspaceGroupOrder: 1,
    workspaceOrder: 3,
    icon: 'DocumentChecked',
    operation: 'query',
    roles: [ROLE_KEYS.SYSTEM_ADMIN, ROLE_KEYS.DORMITORY_ADMIN, ROLE_KEYS.ZONE_MANAGER],
  },
  {
    id: 'repair-application',
    subsystem: SUBSYSTEM_KEYS.MAINTENANCE,
    routeName: 'RepairApplication',
    path: '/maintenance/reports/create',
    title: '我要报修',
    description: '提交寝室内的维修需求。',
    group: '学生维修服务',
    workspaceGroup: '学生维修服务',
    workspaceGroupOrder: 1,
    workspaceOrder: 1,
    icon: 'EditPen',
    operation: 'create',
    workspaceRoles: [ROLE_KEYS.STUDENT, ROLE_KEYS.ZONE_ADMIN],
    roles: [ROLE_KEYS.SYSTEM_ADMIN, ROLE_KEYS.STUDENT, ROLE_KEYS.ZONE_ADMIN],
  },
  {
    id: 'repair-my-requests',
    subsystem: SUBSYSTEM_KEYS.MAINTENANCE,
    routeName: 'RepairMyRequests',
    path: '/maintenance/my-repairs',
    title: '我的报修',
    description: '查看待完成报修和历史报修记录。',
    group: '学生维修服务',
    workspaceGroup: '学生维修服务',
    workspaceGroupOrder: 1,
    workspaceOrder: 2,
    icon: 'List',
    operation: 'query',
    workspaceRoles: [ROLE_KEYS.STUDENT, ROLE_KEYS.ZONE_ADMIN],
    roles: [ROLE_KEYS.SYSTEM_ADMIN, ROLE_KEYS.STUDENT, ROLE_KEYS.ZONE_ADMIN],
  },
  {
    id: 'repair-issue-records',
    subsystem: SUBSYSTEM_KEYS.MAINTENANCE,
    routeName: 'RepairIssueRecords',
    path: '/maintenance/issues',
    title: '问题记录',
    description: '查看已上报的维修问题及处理进度。',
    group: '问题管理',
    icon: 'List',
    operation: 'query',
    workspaceVisible: false,
    roles: [
      ROLE_KEYS.SYSTEM_ADMIN,
      ROLE_KEYS.DORMITORY_ADMIN,
      ROLE_KEYS.ZONE_MANAGER,
      ROLE_KEYS.STUDENT,
      ROLE_KEYS.ZONE_ADMIN,
    ],
  },
  {
    id: 'repair-work-order-create',
    subsystem: SUBSYSTEM_KEYS.MAINTENANCE,
    routeName: 'RepairWorkOrderCreate',
    path: '/maintenance/work-orders/create',
    title: '创建工单',
    description: '将已上报的问题整理为待审核工单。',
    group: '问题管理',
    icon: 'DocumentAdd',
    operation: 'create',
    workspaceVisible: false,
    roles: [ROLE_KEYS.SYSTEM_ADMIN, ROLE_KEYS.ZONE_MANAGER],
  },
  {
    id: 'repair-history',
    subsystem: SUBSYSTEM_KEYS.MAINTENANCE,
    routeName: 'RepairHistory',
    path: '/maintenance/history',
    title: '维修历史',
    description: '查看已完成的报修问题和维修工单。',
    group: '问题管理',
    icon: 'Clock',
    operation: 'query',
    workspaceVisible: false,
    roles: maintenanceRoles,
  },
  {
    id: 'repair-work-order-pending-review',
    subsystem: SUBSYSTEM_KEYS.MAINTENANCE,
    routeName: 'RepairWorkOrderPendingReview',
    path: '/maintenance/work-orders/pending-review',
    title: '待审核工单',
    description: '查看并编辑等待审核的工单。',
    group: '工单管理',
    icon: 'Tickets',
    operation: 'query',
    workspaceVisible: false,
    roles: [ROLE_KEYS.SYSTEM_ADMIN, ROLE_KEYS.ZONE_MANAGER],
  },
  {
    id: 'repair-work-order-review',
    subsystem: SUBSYSTEM_KEYS.MAINTENANCE,
    routeName: 'RepairWorkOrderReview',
    path: '/maintenance/work-orders/review',
    title: '工单审核',
    description: '审核苑区老师提交的维修工单。',
    group: '工单管理',
    icon: 'CircleCheck',
    operation: 'edit',
    workspaceVisible: false,
    roles: [ROLE_KEYS.SYSTEM_ADMIN, ROLE_KEYS.DORMITORY_ADMIN],
  },
  {
    id: 'repair-work-order-dispatch',
    subsystem: SUBSYSTEM_KEYS.MAINTENANCE,
    routeName: 'RepairWorkOrderDispatch',
    path: '/maintenance/work-orders/dispatch',
    title: '派发工单',
    description: '将审核通过的工单派发至维修人员。',
    group: '工单管理',
    icon: 'Promotion',
    operation: 'edit',
    workspaceVisible: false,
    roles: [ROLE_KEYS.SYSTEM_ADMIN, ROLE_KEYS.ZONE_MANAGER],
  },
  {
    id: 'repair-work-order-pending',
    subsystem: SUBSYSTEM_KEYS.MAINTENANCE,
    routeName: 'RepairWorkOrderPending',
    path: '/maintenance/work-orders/pending',
    title: '待处理工单',
    description: '查看分配给本人的待处理维修工单。',
    group: '工单管理',
    icon: 'Tools',
    operation: 'edit',
    workspaceVisible: false,
    roles: [ROLE_KEYS.SYSTEM_ADMIN, ROLE_KEYS.REPAIR_WORKER, ROLE_KEYS.REPAIR_TEAM],
  },
  {
    id: 'repair-work-order-unaccepted',
    subsystem: SUBSYSTEM_KEYS.MAINTENANCE,
    routeName: 'RepairWorkOrderUnaccepted',
    path: '/maintenance/work-orders/unaccepted',
    title: '未接单工单',
    description: '查看已派发但尚未接单的工单并及时跟进。',
    group: '工单管理',
    icon: 'WarningFilled',
    operation: 'query',
    workspaceVisible: false,
    roles: [ROLE_KEYS.ZONE_MANAGER, ROLE_KEYS.SYSTEM_ADMIN, ROLE_KEYS.DORMITORY_ADMIN],
  },
  {
    id: 'repair-work-order-records',
    subsystem: SUBSYSTEM_KEYS.MAINTENANCE,
    routeName: 'RepairWorkOrderRecords',
    path: '/maintenance/work-orders/records',
    title: '工单记录',
    description: '查看维修工单的完整流转记录。',
    group: '工单管理',
    icon: 'Document',
    operation: 'query',
    workspaceVisible: false,
    roles: [
      ROLE_KEYS.ZONE_MANAGER,
      ROLE_KEYS.SYSTEM_ADMIN,
      ROLE_KEYS.DORMITORY_ADMIN,
      ROLE_KEYS.REPAIR_WORKER,
      ROLE_KEYS.REPAIR_TEAM,
    ],
  },
  {
    id: 'repair-work-order-acceptance',
    subsystem: SUBSYSTEM_KEYS.MAINTENANCE,
    routeName: 'RepairWorkOrderAcceptance',
    path: '/maintenance/work-orders/acceptance',
    title: '验收工单',
    description: '验收已完成的维修工单。',
    group: '工单管理',
    icon: 'Finished',
    operation: 'edit',
    workspaceVisible: false,
    roles: [ROLE_KEYS.SYSTEM_ADMIN, ROLE_KEYS.ZONE_MANAGER],
  },
  {
    id: 'repair-dictionary',
    subsystem: SUBSYSTEM_KEYS.MAINTENANCE,
    routeName: 'RepairDictionary',
    path: '/maintenance/dictionaries',
    title: '报修字典管理',
    description: '维护报修区域及问题类型配置。',
    group: '基础配置',
    icon: 'SetUp',
    operation: 'edit',
    workspaceVisible: false,
    roles: [ROLE_KEYS.SYSTEM_ADMIN],
  },
  {
    id: 'account-management',
    subsystem: SUBSYSTEM_KEYS.SYSTEM,
    routeName: 'AccountManagement',
    path: '/system/accounts',
    title: '用户账号管理',
    description: '维护系统登录账号与角色。',
    group: '系统管理',
    icon: 'UserFilled',
    operation: 'edit',
    roles: [ROLE_KEYS.SYSTEM_ADMIN],
  },
  {
    id: 'room-management',
    subsystem: SUBSYSTEM_KEYS.SYSTEM,
    routeName: 'RoomManagement',
    path: '/system/rooms',
    title: '楼栋与寝室信息管理',
    description: '维护校区、苑区、楼栋和房间信息。',
    group: '系统管理',
    icon: 'OfficeBuilding',
    operation: 'edit',
    roles: [ROLE_KEYS.SYSTEM_ADMIN, ROLE_KEYS.DORMITORY_ADMIN],
  },
  {
    id: 'operation-log',
    subsystem: SUBSYSTEM_KEYS.SYSTEM,
    routeName: 'OperationLog',
    path: '/system/operation-logs',
    title: '系统操作日志',
    description: '查看系统用户的操作记录。',
    group: '系统管理',
    icon: 'Document',
    operation: 'query',
    roles: [ROLE_KEYS.SYSTEM_ADMIN, ROLE_KEYS.DORMITORY_ADMIN],
  },
])

export function getRole(roleKey) {
  return ROLE_OPTIONS.find((role) => role.value === roleKey)
}

export function getSubsystem(subsystemId) {
  return SUBSYSTEMS.find((subsystem) => subsystem.id === subsystemId)
}

export function getSubsystemsForRole(roleKey) {
  return SUBSYSTEMS.filter((subsystem) => subsystem.roles.includes(roleKey))
}

export function getModule(moduleId) {
  return ACCESS_MODULES.find((module) => module.id === moduleId)
}

export function getModulesForRole(roleKey, subsystemId) {
  return ACCESS_MODULES.filter(
    (module) =>
      module.roles.includes(roleKey) &&
      module.workspaceVisible !== false &&
      (!module.workspaceRoles || module.workspaceRoles.includes(roleKey)) &&
      (!subsystemId || module.subsystem === subsystemId),
  ).sort((left, right) => {
    const leftGroupOrder = ACCESS_MODULES.findIndex(
      (module) => module.subsystem === left.subsystem && module.group === left.group,
    )
    const rightGroupOrder = ACCESS_MODULES.findIndex(
      (module) => module.subsystem === right.subsystem && module.group === right.group,
    )

    if (leftGroupOrder !== rightGroupOrder) return leftGroupOrder - rightGroupOrder

    return (
      MODULE_OPERATION_PRIORITY[left.operation] - MODULE_OPERATION_PRIORITY[right.operation]
    )
  })
}

export function getModuleDescription(module, roleKey) {
  return module?.descriptions?.[roleKey] || module?.description || ''
}
